### ISSUE TITLE
Compilation fails at 93%

### ISSUE THREAD

**Issue by bMac244** [N64Recomp/N64Recomp#102]
Trying to build on my Mac (macOS Ventura 13.7) and it fails with the following error. Can someone help?

`[ 93%] Building CXX object CMakeFiles/RecompModTool.dir/RecompModTool/main.cpp.o
/Users/cat1217/N64Recomp/RecompModTool/main.cpp:78:21: error: no member named 'from_chars_result' in namespace 'std'
    std::array<std::from_chars_result, 3> parse_results; 
               ~~~~~^
/Users/cat1217/N64Recomp/RecompModTool/main.cpp:81:29: error: no member named 'from_chars' in namespace 'std'
    parse_results[0] = std::from_chars(str.data() + parse_starts[0], str.data() + parse_ends[0], major);
                       ~~~~~^
/Users/cat1217/N64Recomp/RecompModTool/main.cpp:82:29: error: no member named 'from_chars' in namespace 'std'
    parse_results[1] = std::from_chars(str.data() + parse_starts[1], str.data() + parse_ends[1], minor);
                       ~~~~~^
/Users/cat1217/N64Recomp/RecompModTool/main.cpp:83:29: error: no member named 'from_chars' in namespace 'std'
    parse_results[2] = std::from_chars(str.data() + parse_starts[2], str.data() + parse_ends[2], patch);
                       ~~~~~^
4 errors generated.
gmake[2]: *** [CMakeFiles/RecompModTool.dir/build.make:104: CMakeFiles/RecompModTool.dir/RecompModTool/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:296: CMakeFiles/RecompModTool.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2`

**Comment by Mr-Wiseguy** [comment]
Can you try adding `#include <charconv>` at the includes in the top of that file and see if it fixes it?

**Comment by bMac244** [comment]
Wow that worked. Thanks man.
